# Generated by Django 4.2.3 on 2023-07-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_department_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
